name: conduit_config
description: A safe and convenient way to read YAML configuration files.
version: 1.0.0-b1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit_runtime:
    git: git@github.com:conduit-dart/conduit-runtime.git
  yaml: ^3.1.0

dev_dependencies:
  lint: ^1.5.0
  test: ^1.16.5
